This document analyzes the dataset logged by CARLA's system. The metrics to be measured are the following: 
1. **Reaction Time**
    - This is from the time the alert was sent until the time the driver made an action. This will help the researches know the appropriate time to give an alert. 
2. **Ignored Alert** 
    - This checks whether the driver made an action to the alert or ignored it. This will be used to prove the effectiveness of providing an alert to decrease speed.
3. **Speed Change**
    - This checks the speed. 
4. **Braking Distance**
    - This checks the distance from when the alert was given until the time they made an action. 

*Note: An action made by the driver can be either a release of the throttle or pressing on the brakes.*

In [1]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("cleaned_Sim.csv")

df.head()

,timestamp,phase,speed_kmh,event,details,speed_limit,Location_X,Location_Y,violation_flag,event_id
0,1.771924e+09,4,0.71,WS_SEND,"{""phase"": 4, ""speed"": 0.71, ""speed_limit"": 30,...",30.0,NaN,NaN,0,0
1,1.771924e+09,4,0.71,WS_SEND,"{""phase"": 4, ""speed"": 0.71, ""speed_limit"": 30,...",30.0,NaN,NaN,0,0
2,1.771924e+09,4,0.71,WS_SEND,"{""phase"": 4, ""speed"": 0.71, ""speed_limit"": 30,...",30.0,NaN,NaN,0,0
3,1.771924e+09,4,1.17,WS_SEND,"{""phase"": 4, ""speed"": 1.17, ""speed_limit"": 30,...",30.0,NaN,NaN,0,0
4,1.771924e+09,4,1.19,WS_SEND,"{""phase"": 4, ""speed"": 1.19, ""speed_limit"": 30,...",30.0,NaN,NaN,0,0

### Reaction Time

### Ignored Alert

### Speed Change

### Braking Distance

In [3]:
# Transfer to Sim Analysis

#Baseline
df_NC = df[df['phase'] == 1]
display(df_NC)

# Audio Only 
df_AO = df[df['phase'] == 2]
#display(df_AO)

# Haptic Only
df_HO = df[df['phase'] == 3]
#display(df_HO)

# Combination Haptic and Audio
df_HA = df[df['phase'] == 4]
#display(df_HA)

,timestamp,phase,speed_kmh,event,details,speed_limit,Location_X,Location_Y,violation_flag,event_id
7122,1.771924e+09,1,37.14,REACTION,action=REDUCE_THROTTLE|time=0.21s|control={'th...,NaN,NaN,NaN,0,0
7123,1.771924e+09,1,37.14,SPEED_VIOLATION,Speed 37.14 km/h > limit 30.00 km/h at Locatio...,30.0,-85.912148,35.437183,1,4
7124,1.771924e+09,1,36.53,REACTION,action=VIOLATION_RESOLVED|time=0.26s|reaction_...,NaN,NaN,NaN,-1,0
7125,1.771924e+09,1,14.79,YELLOW_LIGHT_PASS,"Passed yellow at Location(x=-85.075447, y=113....",NaN,-85.075447,113.654617,0,0
7126,1.771924e+09,1,19.89,RED_LIGHT_VIOLATION,TrafficLight Violation at Location(x=-22.61465...,NaN,-22.614655,136.981354,0,0
...,...,...,...,...,...,...,...,...,...,...
437869,1.771680e+09,1,36.00,REACTION,action=VIOLATION_RESOLVED|time=1.78s|reaction_...,NaN,NaN,NaN,-1,0
437870,1.771680e+09,1,37.01,SPEED_VIOLATION,Speed 37.01 km/h > limit 30.00 km/h at Locatio...,30.0,-142.610382,118.224449,1,887
437871,1.771680e+09,1,36.70,REACTION,action=VIOLATION_RESOLVED|time=0.15s|reaction_...,NaN,NaN,NaN,-1,0
437872,1.771680e+09,1,475.51,PHASE_STOP,Baseline,NaN,NaN,NaN,0,0
437873,1.771680e+09,1,475.51,PHASE_STOP,Baseline,NaN,NaN,NaN,0,0

In [5]:
#speeding_count = df["overspeed"].sum()
#VIOLATION COUNTS
speeding_count = df[df["event"] == "SPEED_VIOLATION"].shape[0]
stoplight_countRed = df[df["event"] == "RED_LIGHT_VIOLATION"].shape[0]
stoplight_countYellow = df[df["event"] == "YELLOW_LIGHT_PASS"].shape[0]
print("Speed count: ", speeding_count)
print("Red Light count: ", stoplight_countRed)
print("Yellow Light count: ", stoplight_countYellow)

Speed count:  926
Red Light count:  44033
Yellow Light count:  91