In [2]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("cleaned_Sim.csv")

df.head()

/var/folders/s7/6zmqmfgn45v2bblppz_50xmr0000gq/T/ipykernel_1926/1777772689.py:1: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("cleaned_Sim.csv")

,timestamp,phase,scenario,speed_kmh,event,details,parsed,speed_limit,overspeed,alert
0,1.771922e+09,4,START,0.0,PHASE_START,Assisted-AH,{},NaN,NaN,NaN
1,1.771923e+09,4,START,0.0,PHASE_START,Assisted-AH,{},NaN,NaN,NaN
2,1.771923e+09,4,WEBSOCKET,0.0,WS_SEND,"{""phase"": 4, ""speed"": 0.0, ""speed_limit"": 30, ...","{'phase': 4, 'speed': 0.0, 'speed_limit': 30, ...",30.0,False,NaN
3,1.771923e+09,4,WEBSOCKET,0.0,WS_SEND,"{""phase"": 4, ""speed"": 0.0, ""speed_limit"": 30, ...","{'phase': 4, 'speed': 0.0, 'speed_limit': 30, ...",30.0,False,NaN
4,1.771923e+09,4,WEBSOCKET,0.0,WS_SEND,"{""phase"": 4, ""speed"": 0.0, ""speed_limit"": 30, ...","{'phase': 4, 'speed': 0.0, 'speed_limit': 30, ...",30.0,False,NaN

In [4]:
# Transfer to Sim Analysis

#Baseline
df_NC = df[df['phase'] == 1]
display(df_NC)

# Audio Only 
df_AO = df[df['phase'] == 2]
#display(df_AO)

# Haptic Only
df_HO = df[df['phase'] == 3]
#display(df_HO)

# Combination Haptic and Audio
df_HA = df[df['phase'] == 4]
#display(df_HA)

,timestamp,phase,scenario,speed_kmh,event,details,parsed,speed_limit,overspeed,alert
9531,1.771924e+09,1,START,0.00,PHASE_START,Baseline,{},NaN,NaN,NaN
9532,1.771924e+09,1,START,0.00,PHASE_START,Baseline,{},NaN,NaN,NaN
9533,1.771924e+09,1,SPEED_LIMIT,37.14,REACTION,action=REDUCE_THROTTLE|time=0.21s|control={'th...,{},NaN,NaN,NaN
9534,1.771924e+09,1,SPEED_LIMIT,37.14,SPEED_VIOLATION,Speed 37.14 km/h > limit 30.00 km/h at Locatio...,{},NaN,NaN,NaN
9535,1.771924e+09,1,SPEED_LIMIT,36.53,REACTION,action=VIOLATION_RESOLVED|time=0.26s|reaction_...,{},NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
735622,1.771680e+09,1,SPEED_LIMIT,36.00,REACTION,action=VIOLATION_RESOLVED|time=1.78s|reaction_...,{},NaN,NaN,NaN
735623,1.771680e+09,1,SPEED_LIMIT,37.01,SPEED_VIOLATION,Speed 37.01 km/h > limit 30.00 km/h at Locatio...,{},NaN,NaN,NaN
735624,1.771680e+09,1,SPEED_LIMIT,36.70,REACTION,action=VIOLATION_RESOLVED|time=0.15s|reaction_...,{},NaN,NaN,NaN
735625,1.771680e+09,1,STOP,475.51,PHASE_STOP,Baseline,{},NaN,NaN,NaN
735626,1.771680e+09,1,STOP,475.51,PHASE_STOP,Baseline,{},NaN,NaN,NaN

In [12]:
df["event"].unique()

array(['PHASE_START', 'WS_SEND', 'YELLOW_LIGHT_PASS', 'REACTION',
       'SPEED_VIOLATION', 'RED_LIGHT_VIOLATION', 'PHASE_STOP', 'HUD_CUE'],
      dtype=object)

In [16]:
#speeding_count = df["overspeed"].sum()
speeding_count = df[df["event"] == "SPEED_VIOLATION"].shape[0]
stoplight_countRed = df[df["event"] == "RED_LIGHT_VIOLATION"].shape[0]
stoplight_countYellow = df[df["event"] == "YELLOW_LIGHT_PASS"].shape[0]
print("Speed count: ", speeding_count)
print("Red Light count: ", stoplight_countRed)
print("Yellow Light count: ", stoplight_countYellow)

Speed count:  926
Red Light count:  44033
Yellow Light count:  91